### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by zesterer** [Nils-TUD/Escape#10]
You're the only other person other than me I've ever seen use Scons as a build system for an OS project.

**Comment by Nils-TUD** [comment]
Yes, that seems to happen rarely. But I'm using it for all of my OS projects now and am really happy with it, because it gives me roughly the same control as make, but results in much less build system code since many things work out of the box. And writing python code is also much nicer than writing Makefiles :)

**Comment by zesterer** [comment]
I agree, although personally I've switched to 'tup' ( http://gittup.org/tup/ ). It's very similar, more efficient that makefiles, and has a simple syntax.
